name: HOA Social Automation

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # -------------------------
      # 🔐 Inject Secrets as Files/Env Vars
      # -------------------------

      - name: Write Google Service Account JSON
        run: |
          echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}" > google_sa.json

      - name: Export API keys and config
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/google_sa.json" >> $GITHUB_ENV
          echo "GOOGLE_CALENDAR_ID=${{ secrets.GOOGLE_CALENDAR_ID }}" >> $GITHUB_ENV
          echo "GOOGLE_DRIVE_FOLDER_ID=${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}" >> $GITHUB_ENV
          echo "GMAIL_SENDER=${{ secrets.GMAIL_SENDER }}" >> $GITHUB_ENV
          echo "FACEBOOK_PAGE_ID=${{ secrets.FACEBOOK_PAGE_ID }}" >> $GITHUB_ENV
          echo "FACEBOOK_PAGE_ACCESS_TOKEN=${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> $GITHUB_ENV

      # -------------------------
      # ▶️ RUN PYTHON AUTOMATION
      # -------------------------
      - name: Run automation script
        run: python main.py
